### ISSUE TITLE
language server doesn't support it.

### ISSUE THREAD

**Issue by Changki-Kim** [y103kim/setup-env#2]
Hello. YW .  I have Q again : )
``
[coc.nvim]: Error on "jumpDefinition": definition provider not found for current buffer, your language server doesn't support it.
``
When I opened the code, I pressed 'gd' for jumping to definition. But I encountered error message.
I checked the coc-settings.json, there is only golang.
``
  "languageserver": {  
    "golang": {  
      "command": "~/go/bin/gopls",  
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],  
      "filetypes": ["go"]  
    }  
  },  
``

When I searched in google, I can't find solution T.T.

**Comment by y103kim** [comment]
Hi! What lang did you try `gd`?
